MNT Update modules list, remove scrutinizer/codecov from table.
silverstripe/supported-modules pull request #16
Opened 2022-07-11 00:47 UTC by GuySartorelli

This PR makes the following changes:
- Set addons to `false` where the module doesn't appear on addons.silverstripe.org
- Remove deprecated or archived modules
- Add new recipes that replace the CWP ones
- Remove the scrutinizer and codecov badges from the table, as those are no longer used

## Parent issues
- https://github.com/silverstripeltd/product-issues/issues/490
- https://github.com/silverstripe/silverstripe-framework/issues/10233

2022-07-11 00:48 UTC, GuySartorelli commented
This must be merged before I can update the list on the website.

2022-07-11 23:54 UTC, maxime-rainville requested changes
Can we remove all the CMS3 module? 

silverstripe/dms
silverstripe/dms-cart
silverstripe/secureassets	
silverstripe/selectupload	
silverstripe/translatable	
symbiote/silverstripe-versionedfiles

2022-07-12 00:00 UTC, GuySartorelli commented
Done

2022-07-12 10:29 UTC, maxime-rainville approved these changes

2022-07-12 10:29 UTC, merged