NEW Make a unified JSON file for all CMS versions
silverstripe/supported-modules pull request #28
Opened 2024-04-29 02:36 UTC by GuySartorelli

TODO:
- add composer.json so this can be added to packagist
- add lightweight PHP API around the json content based on gha-generate-matrix and gha-merge-ups

## Issue
- https://github.com/silverstripe/rhino/issues/17

2024-05-02 23:54 UTC, GuySartorelli commented on src/BranchLogic.php
> +    }
This is from gha-generate-matrix

2024-05-02 23:54 UTC, GuySartorelli commented on src/BranchLogic.php
> +    ): array {
This is from gha-merge-ups

2024-05-02 23:54 UTC, GuySartorelli commented on src/BranchLogic.php
> +    }
This is from gha-generate-matrix

2024-05-02 23:54 UTC, GuySartorelli commented on src/BranchLogic.php
> +    }
This is from gha-generate-matrix, but I think also includes some logic from gha-merge-ups

2024-05-02 23:54 UTC, GuySartorelli commented on src/MetaData.php
> +    ];
Migrated from gha-generate-matrix so we can use PHP constraints as a fallback for identifying the correct CMS major.
We ignore the minor versions in the logic in this repo, but generate-matrix needs them and it doesn't make sense to maintain the list in two places.

2024-05-02 23:54 UTC, GuySartorelli commented on src/MetaData.php
> +    ];
Migrated from gha-merge-ups. Originally only had linkfield in here, but due to changes in the logic these others are needed as well - reasoning in the phpdoc comment.

2024-05-02 23:54 UTC, GuySartorelli commented on src/MetaData.php
> +    ];
Cow is a bit weird - it has branches and tags that make it look like it should have merge-ups, but in reality we only ever touch the master branch.

2024-05-02 23:54 UTC, GuySartorelli commented on src/MetaData.php
> +    public static function getMetaDataByPackagistName(string $packagistName): array
Only used by gha-generate-matrix's `hardcoded.php` - but I kept this logic here instead of dumping it in that file in case we find use for it later on, since it's very similar to the method above.

2024-05-02 23:54 UTC, GuySartorelli commented on tests/BranchLogicTest.php
The merge-up scenarios are mostly taken straight from gha-generate-matrix, with a few more added in for scenarios I encountered during development.

The cms major scenarios are adapted from gha-generate-matrix tests, though due to the additional logic that repo has for getting installer versions, I left them intact there as well.

2024-05-02 23:54 UTC, GuySartorelli commented on tests/MetaDataTest.php
> +    public function testGetAllRepositoryMetaData(): void
This test is mostly about validating the schema of the json file - I found a few issues with the data when implementing these tests, so they've already proved their worth.

2024-05-06 01:24 UTC, emteknetnz commented on repositories.json
> +    },
missing behat-extension? https://github.com/silverstripe/supported-modules/blob/4/modules.json#L267

2024-05-06 01:57 UTC, emteknetnz requested changes

2024-05-06 01:57 UTC, emteknetnz commented on repositories.json
> +        "5": ["5"],
```suggestion
        "4": ["4"],
        "5": ["5"],
```

2024-05-06 01:57 UTC, emteknetnz commented on repositories.json
> +    },
missing behat-extension? https://github.com/silverstripe/supported-modules/blob/4/modules.json#L267

2024-05-06 01:57 UTC, emteknetnz commented on repositories.json
> +    {
Need tractorcow/classproxy? https://github.com/silverstripe/supported-modules/blob/4/modules.json#L1092 and proxy-db? https://github.com/silverstripe/supported-modules/blob/4/modules.json#L1114

2024-05-06 01:59 UTC, GuySartorelli commented on repositories.json
> +    {
Those are both marked as "supported-dependency", so the note in the PR description applies. Copied below for your convenience:

> NOTE: Any "supported-dependency" in CMS 4 only which we don't own has been intentionally excluded from the new json file. e.g. we aren't listing `composer/installers` in there, which was in the file from the `4` branch.

2024-05-06 02:00 UTC, GuySartorelli commented on repositories.json
> +    },
You mean https://github.com/silverstripe/supported-modules/blob/26231d75b4ccb4c72eecfa8a8a1457d6cfbe57e8/repositories.json#L1401-L1409 ?

2024-05-06 02:05 UTC, GuySartorelli commented on repositories.json
> +        "5": ["5"],
Done

2024-05-06 06:10 UTC, emteknetnz approved these changes

2024-05-06 06:10 UTC, merged