DOC Update readme
silverstripe/supported-modules pull request #43
Opened 2024-10-17 00:19 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/pull/11429

2024-10-17 02:37 UTC, GuySartorelli requested changes

2024-10-17 02:37 UTC, GuySartorelli commented on README.md
> +> Only the `main` branch of this repository is maintained. Stable tags must be manually created from the `main` branch. There is no auto tagging via a GitHub action. The `3`, `4`, and `5` branches ar
```suggestion
> Only the `main` branch of this repository is maintained. Stable tags must be manually created from the `main` branch. There is no auto tagging via a GitHub action. All branches other than `main` are legacy and should not be referenced going forward.
```

2024-10-17 21:06 UTC, emteknetnz commented on README.md
> +> Only the `main` branch of this repository is maintained. Stable tags must be manually created from the `main` branch. There is no auto tagging via a GitHub action. The `3`, `4`, and `5` branches ar
Updated

2024-10-20 20:03 UTC, GuySartorelli requested changes

2024-10-20 20:03 UTC, GuySartorelli commented on src/MetaData.php
> +    private static function getRepositoryMetaDataInner(bool $categorised = true, bool $doFetch = true): array
Please just add a new optional param to the existing method instead. This repo isn't protected by our supported modules policies and there's 0 chance someone is subclassing this so it isn't a breaking change.

2024-10-20 21:20 UTC, emteknetnz commented on src/MetaData.php
> +    private static function getRepositoryMetaDataInner(bool $categorised = true, bool $doFetch = true): array
Updated

2024-10-21 00:44 UTC, GuySartorelli approved these changes
LGTM

2024-10-21 00:44 UTC, merged